// Code Generated by Sidekick is for learning and experimentation purposes only.

const express = require("express");
const fetch = require("node-fetch");

const app = express();
const url = "https://jsonplaceholder.typicode.com/comments";

async function testing(req, res) {
    try {
        const response = await fetch(url);
        const data = await response.json();
        console.log(data);
        // res.send(data);
    } catch (error) {
        console.error("Fetch error:", error);
        res.status(500).send("Internal Server Error");
    }
}

module.exports = testing;
